### ISSUE TITLE
Brew doctor warning on brew-caveats - file outside formula directory

### ISSUE THREAD

**Issue by kambale** [rafaelgarrido/homebrew-caveats#2]
I have been unable to fix a warning error from brew doctor as it relates to caveats.

The error I get is

Warning: Found Ruby file outside rafaelgarrido/caveats tap formula directory
(/usr/local/Homebrew/Library/Taps/rafaelgarrido/homebrew-caveats/Formula):
  /usr/local/Homebrew/Library/Taps/rafaelgarrido/homebrew-caveats/brew-caveats.rb

**Comment by rafaelgarrido** [comment]
@kambale Thank you for the heads up and sorry for taking too long to address this annoying warning. I just released 0.0.6 and the message should be gone by now. A simple brew update/upgrade will give you the new version. Please let me know if you have any trouble.
